spring: 
  application:
    name: game-mongo-record
    serverId: 101  #服务器id
  data:
    mongodb:
      #uri: mongodb://192.168.3.220:27018/slotgame
      database: slotgame
      host: 192.168.3.220
      port: 27017
      username: slotgame
      password: HF5HFi9CwIIXGazs
rocketmq:  #前面没有spring
  nameServer: 192.168.3.220:9876 #
  producer: 
    group: producer-group  #
    