// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot.proto

package com.frame.protobuf;

public final class RobotMsg {
  private RobotMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *特殊协议号
   * </pre>
   *
   * Protobuf enum {@code SubCmd}
   */
  public enum SubCmd
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *网络命令开始,暂没使用
     * </pre>
     *
     * <code>Cmd_Begin = 0;</code>
     */
    Cmd_Begin(0),
    /**
     * <pre>
     *机器人请求登录gateway
     * </pre>
     *
     * <code>Cmd_ReqRobotLogin = -1;</code>
     */
    Cmd_ReqRobotLogin(-1),
    /**
     * <pre>
     *机器人请求登录gateway返回
     * </pre>
     *
     * <code>Cmd_PushRobotLogin = -2;</code>
     */
    Cmd_PushRobotLogin(-2),
    /**
     * <pre>
     *机器人请求登录游戏
     * </pre>
     *
     * <code>Cmd_ReqRobotLoginGame = -3;</code>
     */
    Cmd_ReqRobotLoginGame(-3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *网络命令开始,暂没使用
     * </pre>
     *
     * <code>Cmd_Begin = 0;</code>
     */
    public static final int Cmd_Begin_VALUE = 0;
    /**
     * <pre>
     *机器人请求登录gateway
     * </pre>
     *
     * <code>Cmd_ReqRobotLogin = -1;</code>
     */
    public static final int Cmd_ReqRobotLogin_VALUE = -1;
    /**
     * <pre>
     *机器人请求登录gateway返回
     * </pre>
     *
     * <code>Cmd_PushRobotLogin = -2;</code>
     */
    public static final int Cmd_PushRobotLogin_VALUE = -2;
    /**
     * <pre>
     *机器人请求登录游戏
     * </pre>
     *
     * <code>Cmd_ReqRobotLoginGame = -3;</code>
     */
    public static final int Cmd_ReqRobotLoginGame_VALUE = -3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SubCmd valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SubCmd forNumber(int value) {
      switch (value) {
        case 0: return Cmd_Begin;
        case -1: return Cmd_ReqRobotLogin;
        case -2: return Cmd_PushRobotLogin;
        case -3: return Cmd_ReqRobotLoginGame;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SubCmd>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SubCmd> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SubCmd>() {
            public SubCmd findValueByNumber(int number) {
              return SubCmd.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.frame.protobuf.RobotMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final SubCmd[] VALUES = values();

    public static SubCmd valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SubCmd(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SubCmd)
  }

  public interface ReqRobotLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReqRobotLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *玩家id
     * </pre>
     *
     * <code>string pid = 1;</code>
     * @return The pid.
     */
    java.lang.String getPid();
    /**
     * <pre>
     *玩家id
     * </pre>
     *
     * <code>string pid = 1;</code>
     * @return The bytes for pid.
     */
    com.google.protobuf.ByteString
        getPidBytes();

    /**
     * <code>string token = 2;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 2;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * <pre>
   *机器人请求登录gateway
   * </pre>
   *
   * Protobuf type {@code ReqRobotLogin}
   */
  public static final class ReqRobotLogin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReqRobotLogin)
      ReqRobotLoginOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReqRobotLogin.newBuilder() to construct.
    private ReqRobotLogin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqRobotLogin() {
      pid_ = "";
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReqRobotLogin();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReqRobotLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              pid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.frame.protobuf.RobotMsg.internal_static_ReqRobotLogin_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.frame.protobuf.RobotMsg.internal_static_ReqRobotLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.frame.protobuf.RobotMsg.ReqRobotLogin.class, com.frame.protobuf.RobotMsg.ReqRobotLogin.Builder.class);
    }

    public static final int PID_FIELD_NUMBER = 1;
    private volatile java.lang.Object pid_;
    /**
     * <pre>
     *玩家id
     * </pre>
     *
     * <code>string pid = 1;</code>
     * @return The pid.
     */
    @java.lang.Override
    public java.lang.String getPid() {
      java.lang.Object ref = pid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *玩家id
     * </pre>
     *
     * <code>string pid = 1;</code>
     * @return The bytes for pid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPidBytes() {
      java.lang.Object ref = pid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 2;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 2;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.frame.protobuf.RobotMsg.ReqRobotLogin)) {
        return super.equals(obj);
      }
      com.frame.protobuf.RobotMsg.ReqRobotLogin other = (com.frame.protobuf.RobotMsg.ReqRobotLogin) obj;

      if (!getPid()
          .equals(other.getPid())) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PID_FIELD_NUMBER;
      hash = (53 * hash) + getPid().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.frame.protobuf.RobotMsg.ReqRobotLogin parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLogin parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.frame.protobuf.RobotMsg.ReqRobotLogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *机器人请求登录gateway
     * </pre>
     *
     * Protobuf type {@code ReqRobotLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReqRobotLogin)
        com.frame.protobuf.RobotMsg.ReqRobotLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.frame.protobuf.RobotMsg.internal_static_ReqRobotLogin_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.frame.protobuf.RobotMsg.internal_static_ReqRobotLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.frame.protobuf.RobotMsg.ReqRobotLogin.class, com.frame.protobuf.RobotMsg.ReqRobotLogin.Builder.class);
      }

      // Construct using com.frame.protobuf.RobotMsg.ReqRobotLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pid_ = "";

        token_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.frame.protobuf.RobotMsg.internal_static_ReqRobotLogin_descriptor;
      }

      @java.lang.Override
      public com.frame.protobuf.RobotMsg.ReqRobotLogin getDefaultInstanceForType() {
        return com.frame.protobuf.RobotMsg.ReqRobotLogin.getDefaultInstance();
      }

      @java.lang.Override
      public com.frame.protobuf.RobotMsg.ReqRobotLogin build() {
        com.frame.protobuf.RobotMsg.ReqRobotLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.frame.protobuf.RobotMsg.ReqRobotLogin buildPartial() {
        com.frame.protobuf.RobotMsg.ReqRobotLogin result = new com.frame.protobuf.RobotMsg.ReqRobotLogin(this);
        result.pid_ = pid_;
        result.token_ = token_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.frame.protobuf.RobotMsg.ReqRobotLogin) {
          return mergeFrom((com.frame.protobuf.RobotMsg.ReqRobotLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.frame.protobuf.RobotMsg.ReqRobotLogin other) {
        if (other == com.frame.protobuf.RobotMsg.ReqRobotLogin.getDefaultInstance()) return this;
        if (!other.getPid().isEmpty()) {
          pid_ = other.pid_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.frame.protobuf.RobotMsg.ReqRobotLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.frame.protobuf.RobotMsg.ReqRobotLogin) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object pid_ = "";
      /**
       * <pre>
       *玩家id
       * </pre>
       *
       * <code>string pid = 1;</code>
       * @return The pid.
       */
      public java.lang.String getPid() {
        java.lang.Object ref = pid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *玩家id
       * </pre>
       *
       * <code>string pid = 1;</code>
       * @return The bytes for pid.
       */
      public com.google.protobuf.ByteString
          getPidBytes() {
        java.lang.Object ref = pid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *玩家id
       * </pre>
       *
       * <code>string pid = 1;</code>
       * @param value The pid to set.
       * @return This builder for chaining.
       */
      public Builder setPid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *玩家id
       * </pre>
       *
       * <code>string pid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPid() {
        
        pid_ = getDefaultInstance().getPid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *玩家id
       * </pre>
       *
       * <code>string pid = 1;</code>
       * @param value The bytes for pid to set.
       * @return This builder for chaining.
       */
      public Builder setPidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 2;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReqRobotLogin)
    }

    // @@protoc_insertion_point(class_scope:ReqRobotLogin)
    private static final com.frame.protobuf.RobotMsg.ReqRobotLogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.frame.protobuf.RobotMsg.ReqRobotLogin();
    }

    public static com.frame.protobuf.RobotMsg.ReqRobotLogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqRobotLogin>
        PARSER = new com.google.protobuf.AbstractParser<ReqRobotLogin>() {
      @java.lang.Override
      public ReqRobotLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqRobotLogin(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqRobotLogin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqRobotLogin> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.frame.protobuf.RobotMsg.ReqRobotLogin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PushRobotLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PushRobotLogin)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *机器人请求登录gateway返回
   * </pre>
   *
   * Protobuf type {@code PushRobotLogin}
   */
  public static final class PushRobotLogin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PushRobotLogin)
      PushRobotLoginOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PushRobotLogin.newBuilder() to construct.
    private PushRobotLogin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PushRobotLogin() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PushRobotLogin();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PushRobotLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.frame.protobuf.RobotMsg.internal_static_PushRobotLogin_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.frame.protobuf.RobotMsg.internal_static_PushRobotLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.frame.protobuf.RobotMsg.PushRobotLogin.class, com.frame.protobuf.RobotMsg.PushRobotLogin.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.frame.protobuf.RobotMsg.PushRobotLogin)) {
        return super.equals(obj);
      }
      com.frame.protobuf.RobotMsg.PushRobotLogin other = (com.frame.protobuf.RobotMsg.PushRobotLogin) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.frame.protobuf.RobotMsg.PushRobotLogin parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frame.protobuf.RobotMsg.PushRobotLogin parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frame.protobuf.RobotMsg.PushRobotLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frame.protobuf.RobotMsg.PushRobotLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frame.protobuf.RobotMsg.PushRobotLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frame.protobuf.RobotMsg.PushRobotLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frame.protobuf.RobotMsg.PushRobotLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.frame.protobuf.RobotMsg.PushRobotLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.frame.protobuf.RobotMsg.PushRobotLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.frame.protobuf.RobotMsg.PushRobotLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.frame.protobuf.RobotMsg.PushRobotLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.frame.protobuf.RobotMsg.PushRobotLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.frame.protobuf.RobotMsg.PushRobotLogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *机器人请求登录gateway返回
     * </pre>
     *
     * Protobuf type {@code PushRobotLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PushRobotLogin)
        com.frame.protobuf.RobotMsg.PushRobotLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.frame.protobuf.RobotMsg.internal_static_PushRobotLogin_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.frame.protobuf.RobotMsg.internal_static_PushRobotLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.frame.protobuf.RobotMsg.PushRobotLogin.class, com.frame.protobuf.RobotMsg.PushRobotLogin.Builder.class);
      }

      // Construct using com.frame.protobuf.RobotMsg.PushRobotLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.frame.protobuf.RobotMsg.internal_static_PushRobotLogin_descriptor;
      }

      @java.lang.Override
      public com.frame.protobuf.RobotMsg.PushRobotLogin getDefaultInstanceForType() {
        return com.frame.protobuf.RobotMsg.PushRobotLogin.getDefaultInstance();
      }

      @java.lang.Override
      public com.frame.protobuf.RobotMsg.PushRobotLogin build() {
        com.frame.protobuf.RobotMsg.PushRobotLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.frame.protobuf.RobotMsg.PushRobotLogin buildPartial() {
        com.frame.protobuf.RobotMsg.PushRobotLogin result = new com.frame.protobuf.RobotMsg.PushRobotLogin(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.frame.protobuf.RobotMsg.PushRobotLogin) {
          return mergeFrom((com.frame.protobuf.RobotMsg.PushRobotLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.frame.protobuf.RobotMsg.PushRobotLogin other) {
        if (other == com.frame.protobuf.RobotMsg.PushRobotLogin.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.frame.protobuf.RobotMsg.PushRobotLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.frame.protobuf.RobotMsg.PushRobotLogin) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PushRobotLogin)
    }

    // @@protoc_insertion_point(class_scope:PushRobotLogin)
    private static final com.frame.protobuf.RobotMsg.PushRobotLogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.frame.protobuf.RobotMsg.PushRobotLogin();
    }

    public static com.frame.protobuf.RobotMsg.PushRobotLogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PushRobotLogin>
        PARSER = new com.google.protobuf.AbstractParser<PushRobotLogin>() {
      @java.lang.Override
      public PushRobotLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PushRobotLogin(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PushRobotLogin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PushRobotLogin> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.frame.protobuf.RobotMsg.PushRobotLogin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReqRobotLoginGameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReqRobotLoginGame)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *玩家id
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <pre>
     *玩家id
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *金币额
     * </pre>
     *
     * <code>int64 balance = 3;</code>
     * @return The balance.
     */
    long getBalance();

    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string headPic = 4;</code>
     * @return The headPic.
     */
    java.lang.String getHeadPic();
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string headPic = 4;</code>
     * @return The bytes for headPic.
     */
    com.google.protobuf.ByteString
        getHeadPicBytes();

    /**
     * <pre>
     *头像类型 0原始头像 1道具头像
     * </pre>
     *
     * <code>int32 headPicType = 6;</code>
     * @return The headPicType.
     */
    int getHeadPicType();

    /**
     * <pre>
     *等级
     * </pre>
     *
     * <code>int32 level = 7;</code>
     * @return The level.
     */
    int getLevel();

    /**
     * <pre>
     *房间id初中高级等
     * </pre>
     *
     * <code>int32 roomId = 8;</code>
     * @return The roomId.
     */
    int getRoomId();

    /**
     * <pre>
     *具体进入的桌台号 如果为0 服务器自动分配
     * </pre>
     *
     * <code>int32 deskId = 9;</code>
     * @return The deskId.
     */
    int getDeskId();
  }
  /**
   * <pre>
   *机器人请求登录游戏
   * </pre>
   *
   * Protobuf type {@code ReqRobotLoginGame}
   */
  public static final class ReqRobotLoginGame extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReqRobotLoginGame)
      ReqRobotLoginGameOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReqRobotLoginGame.newBuilder() to construct.
    private ReqRobotLoginGame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqRobotLoginGame() {
      userId_ = "";
      name_ = "";
      headPic_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReqRobotLoginGame();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReqRobotLoginGame(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              balance_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              headPic_ = s;
              break;
            }
            case 48: {

              headPicType_ = input.readInt32();
              break;
            }
            case 56: {

              level_ = input.readInt32();
              break;
            }
            case 64: {

              roomId_ = input.readInt32();
              break;
            }
            case 72: {

              deskId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.frame.protobuf.RobotMsg.internal_static_ReqRobotLoginGame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.frame.protobuf.RobotMsg.internal_static_ReqRobotLoginGame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.frame.protobuf.RobotMsg.ReqRobotLoginGame.class, com.frame.protobuf.RobotMsg.ReqRobotLoginGame.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userId_;
    /**
     * <pre>
     *玩家id
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *玩家id
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BALANCE_FIELD_NUMBER = 3;
    private long balance_;
    /**
     * <pre>
     *金币额
     * </pre>
     *
     * <code>int64 balance = 3;</code>
     * @return The balance.
     */
    @java.lang.Override
    public long getBalance() {
      return balance_;
    }

    public static final int HEADPIC_FIELD_NUMBER = 4;
    private volatile java.lang.Object headPic_;
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string headPic = 4;</code>
     * @return The headPic.
     */
    @java.lang.Override
    public java.lang.String getHeadPic() {
      java.lang.Object ref = headPic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        headPic_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string headPic = 4;</code>
     * @return The bytes for headPic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHeadPicBytes() {
      java.lang.Object ref = headPic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headPic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEADPICTYPE_FIELD_NUMBER = 6;
    private int headPicType_;
    /**
     * <pre>
     *头像类型 0原始头像 1道具头像
     * </pre>
     *
     * <code>int32 headPicType = 6;</code>
     * @return The headPicType.
     */
    @java.lang.Override
    public int getHeadPicType() {
      return headPicType_;
    }

    public static final int LEVEL_FIELD_NUMBER = 7;
    private int level_;
    /**
     * <pre>
     *等级
     * </pre>
     *
     * <code>int32 level = 7;</code>
     * @return The level.
     */
    @java.lang.Override
    public int getLevel() {
      return level_;
    }

    public static final int ROOMID_FIELD_NUMBER = 8;
    private int roomId_;
    /**
     * <pre>
     *房间id初中高级等
     * </pre>
     *
     * <code>int32 roomId = 8;</code>
     * @return The roomId.
     */
    @java.lang.Override
    public int getRoomId() {
      return roomId_;
    }

    public static final int DESKID_FIELD_NUMBER = 9;
    private int deskId_;
    /**
     * <pre>
     *具体进入的桌台号 如果为0 服务器自动分配
     * </pre>
     *
     * <code>int32 deskId = 9;</code>
     * @return The deskId.
     */
    @java.lang.Override
    public int getDeskId() {
      return deskId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (balance_ != 0L) {
        output.writeInt64(3, balance_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(headPic_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, headPic_);
      }
      if (headPicType_ != 0) {
        output.writeInt32(6, headPicType_);
      }
      if (level_ != 0) {
        output.writeInt32(7, level_);
      }
      if (roomId_ != 0) {
        output.writeInt32(8, roomId_);
      }
      if (deskId_ != 0) {
        output.writeInt32(9, deskId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (balance_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, balance_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(headPic_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, headPic_);
      }
      if (headPicType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, headPicType_);
      }
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, level_);
      }
      if (roomId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, roomId_);
      }
      if (deskId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, deskId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.frame.protobuf.RobotMsg.ReqRobotLoginGame)) {
        return super.equals(obj);
      }
      com.frame.protobuf.RobotMsg.ReqRobotLoginGame other = (com.frame.protobuf.RobotMsg.ReqRobotLoginGame) obj;

      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getBalance()
          != other.getBalance()) return false;
      if (!getHeadPic()
          .equals(other.getHeadPic())) return false;
      if (getHeadPicType()
          != other.getHeadPicType()) return false;
      if (getLevel()
          != other.getLevel()) return false;
      if (getRoomId()
          != other.getRoomId()) return false;
      if (getDeskId()
          != other.getDeskId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + BALANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBalance());
      hash = (37 * hash) + HEADPIC_FIELD_NUMBER;
      hash = (53 * hash) + getHeadPic().hashCode();
      hash = (37 * hash) + HEADPICTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getHeadPicType();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      hash = (37 * hash) + ROOMID_FIELD_NUMBER;
      hash = (53 * hash) + getRoomId();
      hash = (37 * hash) + DESKID_FIELD_NUMBER;
      hash = (53 * hash) + getDeskId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.frame.protobuf.RobotMsg.ReqRobotLoginGame parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLoginGame parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLoginGame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLoginGame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLoginGame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLoginGame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLoginGame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLoginGame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLoginGame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLoginGame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLoginGame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.frame.protobuf.RobotMsg.ReqRobotLoginGame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.frame.protobuf.RobotMsg.ReqRobotLoginGame prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *机器人请求登录游戏
     * </pre>
     *
     * Protobuf type {@code ReqRobotLoginGame}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReqRobotLoginGame)
        com.frame.protobuf.RobotMsg.ReqRobotLoginGameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.frame.protobuf.RobotMsg.internal_static_ReqRobotLoginGame_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.frame.protobuf.RobotMsg.internal_static_ReqRobotLoginGame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.frame.protobuf.RobotMsg.ReqRobotLoginGame.class, com.frame.protobuf.RobotMsg.ReqRobotLoginGame.Builder.class);
      }

      // Construct using com.frame.protobuf.RobotMsg.ReqRobotLoginGame.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = "";

        name_ = "";

        balance_ = 0L;

        headPic_ = "";

        headPicType_ = 0;

        level_ = 0;

        roomId_ = 0;

        deskId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.frame.protobuf.RobotMsg.internal_static_ReqRobotLoginGame_descriptor;
      }

      @java.lang.Override
      public com.frame.protobuf.RobotMsg.ReqRobotLoginGame getDefaultInstanceForType() {
        return com.frame.protobuf.RobotMsg.ReqRobotLoginGame.getDefaultInstance();
      }

      @java.lang.Override
      public com.frame.protobuf.RobotMsg.ReqRobotLoginGame build() {
        com.frame.protobuf.RobotMsg.ReqRobotLoginGame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.frame.protobuf.RobotMsg.ReqRobotLoginGame buildPartial() {
        com.frame.protobuf.RobotMsg.ReqRobotLoginGame result = new com.frame.protobuf.RobotMsg.ReqRobotLoginGame(this);
        result.userId_ = userId_;
        result.name_ = name_;
        result.balance_ = balance_;
        result.headPic_ = headPic_;
        result.headPicType_ = headPicType_;
        result.level_ = level_;
        result.roomId_ = roomId_;
        result.deskId_ = deskId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.frame.protobuf.RobotMsg.ReqRobotLoginGame) {
          return mergeFrom((com.frame.protobuf.RobotMsg.ReqRobotLoginGame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.frame.protobuf.RobotMsg.ReqRobotLoginGame other) {
        if (other == com.frame.protobuf.RobotMsg.ReqRobotLoginGame.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getBalance() != 0L) {
          setBalance(other.getBalance());
        }
        if (!other.getHeadPic().isEmpty()) {
          headPic_ = other.headPic_;
          onChanged();
        }
        if (other.getHeadPicType() != 0) {
          setHeadPicType(other.getHeadPicType());
        }
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        if (other.getRoomId() != 0) {
          setRoomId(other.getRoomId());
        }
        if (other.getDeskId() != 0) {
          setDeskId(other.getDeskId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.frame.protobuf.RobotMsg.ReqRobotLoginGame parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.frame.protobuf.RobotMsg.ReqRobotLoginGame) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <pre>
       *玩家id
       * </pre>
       *
       * <code>string userId = 1;</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *玩家id
       * </pre>
       *
       * <code>string userId = 1;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *玩家id
       * </pre>
       *
       * <code>string userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *玩家id
       * </pre>
       *
       * <code>string userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *玩家id
       * </pre>
       *
       * <code>string userId = 1;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private long balance_ ;
      /**
       * <pre>
       *金币额
       * </pre>
       *
       * <code>int64 balance = 3;</code>
       * @return The balance.
       */
      @java.lang.Override
      public long getBalance() {
        return balance_;
      }
      /**
       * <pre>
       *金币额
       * </pre>
       *
       * <code>int64 balance = 3;</code>
       * @param value The balance to set.
       * @return This builder for chaining.
       */
      public Builder setBalance(long value) {
        
        balance_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *金币额
       * </pre>
       *
       * <code>int64 balance = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBalance() {
        
        balance_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object headPic_ = "";
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string headPic = 4;</code>
       * @return The headPic.
       */
      public java.lang.String getHeadPic() {
        java.lang.Object ref = headPic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          headPic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string headPic = 4;</code>
       * @return The bytes for headPic.
       */
      public com.google.protobuf.ByteString
          getHeadPicBytes() {
        java.lang.Object ref = headPic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headPic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string headPic = 4;</code>
       * @param value The headPic to set.
       * @return This builder for chaining.
       */
      public Builder setHeadPic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        headPic_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string headPic = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeadPic() {
        
        headPic_ = getDefaultInstance().getHeadPic();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string headPic = 4;</code>
       * @param value The bytes for headPic to set.
       * @return This builder for chaining.
       */
      public Builder setHeadPicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        headPic_ = value;
        onChanged();
        return this;
      }

      private int headPicType_ ;
      /**
       * <pre>
       *头像类型 0原始头像 1道具头像
       * </pre>
       *
       * <code>int32 headPicType = 6;</code>
       * @return The headPicType.
       */
      @java.lang.Override
      public int getHeadPicType() {
        return headPicType_;
      }
      /**
       * <pre>
       *头像类型 0原始头像 1道具头像
       * </pre>
       *
       * <code>int32 headPicType = 6;</code>
       * @param value The headPicType to set.
       * @return This builder for chaining.
       */
      public Builder setHeadPicType(int value) {
        
        headPicType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像类型 0原始头像 1道具头像
       * </pre>
       *
       * <code>int32 headPicType = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeadPicType() {
        
        headPicType_ = 0;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <pre>
       *等级
       * </pre>
       *
       * <code>int32 level = 7;</code>
       * @return The level.
       */
      @java.lang.Override
      public int getLevel() {
        return level_;
      }
      /**
       * <pre>
       *等级
       * </pre>
       *
       * <code>int32 level = 7;</code>
       * @param value The level to set.
       * @return This builder for chaining.
       */
      public Builder setLevel(int value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *等级
       * </pre>
       *
       * <code>int32 level = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }

      private int roomId_ ;
      /**
       * <pre>
       *房间id初中高级等
       * </pre>
       *
       * <code>int32 roomId = 8;</code>
       * @return The roomId.
       */
      @java.lang.Override
      public int getRoomId() {
        return roomId_;
      }
      /**
       * <pre>
       *房间id初中高级等
       * </pre>
       *
       * <code>int32 roomId = 8;</code>
       * @param value The roomId to set.
       * @return This builder for chaining.
       */
      public Builder setRoomId(int value) {
        
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *房间id初中高级等
       * </pre>
       *
       * <code>int32 roomId = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomId() {
        
        roomId_ = 0;
        onChanged();
        return this;
      }

      private int deskId_ ;
      /**
       * <pre>
       *具体进入的桌台号 如果为0 服务器自动分配
       * </pre>
       *
       * <code>int32 deskId = 9;</code>
       * @return The deskId.
       */
      @java.lang.Override
      public int getDeskId() {
        return deskId_;
      }
      /**
       * <pre>
       *具体进入的桌台号 如果为0 服务器自动分配
       * </pre>
       *
       * <code>int32 deskId = 9;</code>
       * @param value The deskId to set.
       * @return This builder for chaining.
       */
      public Builder setDeskId(int value) {
        
        deskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *具体进入的桌台号 如果为0 服务器自动分配
       * </pre>
       *
       * <code>int32 deskId = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeskId() {
        
        deskId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReqRobotLoginGame)
    }

    // @@protoc_insertion_point(class_scope:ReqRobotLoginGame)
    private static final com.frame.protobuf.RobotMsg.ReqRobotLoginGame DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.frame.protobuf.RobotMsg.ReqRobotLoginGame();
    }

    public static com.frame.protobuf.RobotMsg.ReqRobotLoginGame getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqRobotLoginGame>
        PARSER = new com.google.protobuf.AbstractParser<ReqRobotLoginGame>() {
      @java.lang.Override
      public ReqRobotLoginGame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqRobotLoginGame(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqRobotLoginGame> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqRobotLoginGame> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.frame.protobuf.RobotMsg.ReqRobotLoginGame getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqRobotLogin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReqRobotLogin_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PushRobotLogin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PushRobotLogin_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqRobotLoginGame_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReqRobotLoginGame_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013robot.proto\"+\n\rReqRobotLogin\022\013\n\003pid\030\001 " +
      "\001(\t\022\r\n\005token\030\002 \001(\t\"\020\n\016PushRobotLogin\"\227\001\n" +
      "\021ReqRobotLoginGame\022\016\n\006userId\030\001 \001(\t\022\014\n\004na" +
      "me\030\002 \001(\t\022\017\n\007balance\030\003 \001(\003\022\017\n\007headPic\030\004 \001" +
      "(\t\022\023\n\013headPicType\030\006 \001(\005\022\r\n\005level\030\007 \001(\005\022\016" +
      "\n\006roomId\030\010 \001(\005\022\016\n\006deskId\030\t \001(\005*|\n\006SubCmd" +
      "\022\r\n\tCmd_Begin\020\000\022\036\n\021Cmd_ReqRobotLogin\020\377\377\377" +
      "\377\377\377\377\377\377\001\022\037\n\022Cmd_PushRobotLogin\020\376\377\377\377\377\377\377\377\377\001" +
      "\022\"\n\025Cmd_ReqRobotLoginGame\020\375\377\377\377\377\377\377\377\377\001B\036\n\022" +
      "com.frame.protobufB\010RobotMsgb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ReqRobotLogin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReqRobotLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReqRobotLogin_descriptor,
        new java.lang.String[] { "Pid", "Token", });
    internal_static_PushRobotLogin_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PushRobotLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PushRobotLogin_descriptor,
        new java.lang.String[] { });
    internal_static_ReqRobotLoginGame_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ReqRobotLoginGame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReqRobotLoginGame_descriptor,
        new java.lang.String[] { "UserId", "Name", "Balance", "HeadPic", "HeadPicType", "Level", "RoomId", "DeskId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
